### PR TITLE
Fix handling for split TXT records

### PR DESCRIPTION
**Pull request by cschramm**
See e.g. facebookmail.com or mail.ru.

### CODE REVIEW

**Comment by nathandines** [comment]
Hey Chris,

Thank you for raising this bug. I've taken a look at your pull request, and unfortunately, this would join all TXT records for a domain, not just SPF related TXT records.

I've written up a fix for the split TXT records which also includes the appropriate test cases. It can be found at the following branch: https://github.com/nathandines/SPF2IP/tree/split-spf-record-support

Please clone this down and let me know if this fixes your issue. I'll then create and publish a new release :)

**Comment by cschramm** [comment]
Hey Nathan,

I don't see the problem with my patch but yours should have the same effect and moving the join into the request function makes sense. I'll report back when I had the chance to test it.

**Comment by nathandines** [comment]
~The main issue was with the original implementation of TXT record handling.~

~The TXT records of a domain were being presented by `dns.resolver` as a list of lists (Split TXT records). I hadn't originally realised that this was to cater for split TXT records, and so was presenting all of the split TXT records with the non-split TXT records in a single large list. This becomes problematic when a domain has TXT records which are split, as these records would be indistinguishable from other TXT records (all part of one big list).~

~Basically, each split record need to be concatenated into a single string for presentation as a list of TXT records, rather than a list of TXT record segments.~

~It wasn't specifically an issue with your patch; but your patch highlighted an existing issue in the code.~

EDIT: It's actually been a while since I had looked at this code... looking at it again with fresh eyes this morning, it seems this build might have failed due to some tests being written incorrectly, rather than the code treating the data incorrectly. I think your patch would have been perfectly valid, but the tests for multiple TXT records needed to be corrected.

**Comment by cschramm** [comment]
👍 We're on the same track now. To be honest I did not take a look at the tests at all. I can confirm your patch works fine as well and am looking forward to get a pip-installable version with it. 🙂

**Comment by nathandines** [comment]
Thanks for the discussion Chris; version 1.0.4 which covers this use case has been released :)

**Pull request closed without merging**
